name: Build static site (downloadable)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print tree (before)
        run: |
          pwd
          ls -la
          test -f _config.yaml && echo "_config.yaml found" || echo "NO _config.yaml!"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install deps
        run: |
          bundle config set path 'vendor/bundle'
          bundle install --without development

      - name: Build (appsrv)
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll --version
          bundle exec jekyll build --trace --verbose \
            --config _config.yaml,_config_appsrv.yml \
            --destination ./_site_appsrv
          echo "List _site_appsrv:"
          ls -la _site_appsrv || (echo ">> _site_appsrv NOT FOUND" && exit 1)

      - name: Build (root)
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --trace --verbose \
            --config _config.yaml,_config_root.yml \
            --destination ./_site_root
          echo "List _site_root:"
          ls -la _site_root || (echo ">> _site_root NOT FOUND" && exit 1)

      - name: Upload artifact (appsrv)
        uses: actions/upload-artifact@v4
        with:
          name: homepage
          path: homepage/
          if-no-files-found: error

      - name: Upload artifact (root)
        uses: actions/upload-artifact@v4
        with:
          name: site-root
          path: _site_root/
          if-no-files-found: error
